_target_: models.tasks.ego4d.mq.MQTask

name: ego4d/mq

input_size: ${model.hidden_size}
features_size: 768

num_classes: 110

defaults:
  - /classifier: MLP
  - /regressor: MLP

cls_loss: focal

depth: 8

dropout: 0

pool_features: mean  # max or mean

# Weights for classification and regression losses
weight_cls: 1.0
weight_reg: 1.0
loss_weight: 1.0

# Update arguments of the classifier
classifier:
  features_size: ${..features_size}
  hidden_size: 512
  n_classes: ${..num_classes}
  dropout: 0


# Update arguments of the regressor
regressor:
  features_size: ${..features_size}
  hidden_size: ${..features_size}
  dropout: 0