###################################
# EgoPack Action Recognition Task #
###################################
defaults:   
  - /task/ego4d/ar@_here_
  - _self_
  
_target_: models.tasks.ego4d.ar.EgoPackARTask

# EgoPack-specific configurations:
fusion_level: features  # Literal['features', 'logits', 'none']
fusion_dropout: 0.1
aux_tasks: null
